HW2 is completed
Drodik/otus-go pull request #2
Opened 2023-04-17 00:09 UTC by Drodik

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов
- [ ] Дополнительное задание реализовано

#### Зачёт от 7 баллов

2023-04-17 20:55 UTC, agneum requested changes
Спасибо за вариант решения.
Хорошая работа, однако есть критичные замечания.

Итого: 4 балла из 10. Возвращаю задачу на доработку

2023-04-17 20:55 UTC, agneum commented on hw02_unpack_string/go.mod
> +module github.com/Drodik/otus-go/tree/master/hw02_unpack_string
```suggestion
module github.com/Drodik/otus-go/hw02_unpack_string
```

`/tree/master/` - не относится к пути модуля, это UI GitHub

2023-04-17 20:55 UTC, agneum commented on hw02_unpack_string/main.go
Зачем в пакете (фактически в библиотеке) функция main и вложенный пакет?

2023-04-17 20:55 UTC, agneum commented on hw02_unpack_string/unpack/unpack.go
> +func Unpack(inputStr string) (string, error) {
Рекомендую упростить функцию и уменьшить количество операций/ветвлений внутри, чтобы исправить замечания линтера

2023-04-17 20:55 UTC, agneum commented on hw02_unpack_string/unpack/unpack.go
> +	for index := 0; index < len(inputStr); index++ {
Такой перебор строки будет некорректно определять символы для строк в мультибайтных кодировках (кириллица, иероглифы, эмоджи). 

Рекомендую использовать слайс из рун или проходить по строке с помощью цикла range

2023-04-17 20:55 UTC, agneum commented on hw02_unpack_string/unpack/unpack.go
> +		number, _ := strconv.Atoi(val)
Ошибки всегда важно обрабатывать

2023-04-18 05:54 UTC, Drodik commented on hw02_unpack_string/unpack/unpack.go
> +	for index := 0; index < len(inputStr); index++ {
я делал вариант перебора через range, но при таком варианте у меня не получается реализовать доп задание. Не понимаю, как обработать экранирование без "перескакивания" элемента

2023-05-02 23:25 UTC, agneum approved these changes
Спасибо за правки.
Итого: 10 баллов из 10. Принято

2023-05-03 06:06 UTC, merged